import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 *  - create an ordered group of docs
 *  - render a sidebar for each doc of that group
 *  - provide next/previous navigation
 *
 * The sidebars can be generated from the filesystem, or explicitly defined here.
 *
 * Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  docsSidebar: [
    'intro',
    {
      type: 'category',
      label: 'Proto.Actor',
      link: {type: 'doc', id: 'ProtoActor/index'},
      items: [
        {
          type: 'category',
          label: 'Actors',
          link: {type: 'doc', id: 'ProtoActor/getting-started'},
          items: [
            {
              type: 'category',
              label: 'Overview',
              link: {type: 'doc', id: 'ProtoActor/what-is-protoactor'},
              items: [
                'ProtoActor/what-is-protoactor',
                'ProtoActor/why-protoactor',
                'ProtoActor/features',
                'ProtoActor/design-principles',
                'ProtoActor/reactive-manifesto',
                'ProtoActor/protoactor-vs-erlang-akka',
                'ProtoActor/actors-vs-queues',
                'ProtoActor/terminology',
                'ProtoActor/getting-started',
                'ProtoActor/hello-world',
                'ProtoActor/training',
                'ProtoActor/books',
                'ProtoActor/core-contrib-components',
                'ProtoActor/mermaid',
              ],
            },
            {
              type: 'category',
              label: 'Core Concepts',
              items: [
                'ProtoActor/actors',
                'ProtoActor/life-cycle',
                'ProtoActor/behaviors',
                'ProtoActor/context',
                'ProtoActor/context-decorator',
                'ProtoActor/props',
                'ProtoActor/spawn',
                'ProtoActor/processes',
                'ProtoActor/pid',
                'ProtoActor/mailboxes',
                'ProtoActor/dispatchers',
                'ProtoActor/routers',
                'ProtoActor/scheduling',
                'ProtoActor/middleware',
                'ProtoActor/communication',
                'ProtoActor/receive-timeout',
                'ProtoActor/eventstream',
              ],
            },
            {
              type: 'category',
              label: 'Messaging',
              items: [
                'ProtoActor/messages',
                {type: 'autogenerated', dirName: 'ProtoActor/messages'},
                'ProtoActor/message-patterns',
                'ProtoActor/envelope-pattern',
                'ProtoActor/ask-pattern',
                'ProtoActor/futures',
                'ProtoActor/asyncsemaphore',
              ],
            },
            {
              type: 'category',
              label: 'Reliability & Supervision',
              items: [
                'ProtoActor/fault-tolerance',
                'ProtoActor/supervision',
                'ProtoActor/supervisor-strategy-recipes',
                'ProtoActor/deadletter',
                'ProtoActor/deadlocks',
              ],
            },
            {
              type: 'category',
              label: 'Performance & Concurrency',
              items: [
                'ProtoActor/limit-concurrency',
                'ProtoActor/backpressure',
                'ProtoActor/work-pulling',
                'ProtoActor/throttle',
                'ProtoActor/throttling',
                'ProtoActor/concurrentkeyvaluestore',
                {type: 'autogenerated', dirName: 'ProtoActor/performance'},
              ],
            },
          ],
        },
        {
          type: 'category',
          label: 'Remote',
          link: {type: 'doc', id: 'ProtoActor/remote'},
          items: [
            'ProtoActor/remote',
            'ProtoActor/remote-spawn',
            'ProtoActor/location-transparency',
            'ProtoActor/service-discovery',
            'ProtoActor/grpc-compression',
            'ProtoActor/grpc-tls',
            'ProtoActor/serialization',
            {type: 'autogenerated', dirName: 'ProtoActor/chatexample'},
          ],
        },
        {
          type: 'category',
          label: 'Cluster',
          link: {type: 'doc', id: 'ProtoActor/cluster'},
          items: [
            'ProtoActor/cluster',
            'ProtoActor/clusterintro/index',
            'ProtoActor/cluster-partitions',
            'ProtoActor/sharding-and-partitioning',
            'ProtoActor/local-affinity',
            'ProtoActor/placement-strategies',
            'ProtoActor/workshop-cluster',
            {type: 'autogenerated', dirName: 'ProtoActor/cluster'},
            {type: 'autogenerated', dirName: 'ProtoActor/clusterintro'},
          ],
        },
        {
          type: 'category',
          label: 'Observability',
          items: [
            'ProtoActor/logging',
            'ProtoActor/metrics',
            'ProtoActor/opentelemetry',
            'ProtoActor/observability-cookbook',
            'ProtoActor/tracing',
            'ProtoActor/health-checks',
          ],
        },
        {
          type: 'category',
          label: 'Persistence',
          link: {type: 'doc', id: 'ProtoActor/persistence'},
          items: [
            'ProtoActor/persistence',
            'ProtoActor/persistence-proto-persistence',
            'ProtoActor/coordinated-persistence',
            'ProtoActor/durability',
            'ProtoActor/idempotency',
          ],
        },
        {
          type: 'category',
          label: 'Testing',
          items: [
            'ProtoActor/integration-tests',
          ],
        },
        {
          type: 'category',
          label: 'Patterns',
          items: [
            'ProtoActor/reenter',
            'ProtoActor/circuit-breaker',
            'ProtoActor/consistency-models',
            'ProtoActor/cap-theorem',
            'ProtoActor/consensus',
            'ProtoActor/collective-access',
            'ProtoActor/money-transfer-saga/index',
          ],
        },
      ],
    },
    {
      type: 'category',
      label: 'Durable Functions',
      items: [{type: 'autogenerated', dirName: 'DurableFunctions'}],
    },
    {
      type: 'category',
      label: 'Jsome',
      items: [{type: 'autogenerated', dirName: 'Jsome'}],
    },
    {
      type: 'category',
      label: 'LiveView',
      items: [{type: 'autogenerated', dirName: 'LiveView'}],
    },
    {
      type: 'category',
      label: 'OcppServer',
      items: [{type: 'autogenerated', dirName: 'OcppServer'}],
    },
    {
      type: 'category',
      label: 'TraceLens',
      items: [{type: 'autogenerated', dirName: 'TraceLens'}],
    },
  ],
};

export default sidebars;
